// Mocks generated by Mockito 5.0.10 from annotations
// in flutter_confluence/test/features/on_boarding/domain/check_auth_use_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_confluence/core/error/failures.dart' as _i5;
import 'package:flutter_confluence/features/onboarding/domain/repositories/on_boarding_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {
  @override
  String toString() => super.toString();
}

/// A class which mocks [OnBoardingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnBoardingRepository extends _i1.Mock
    implements _i3.OnBoardingRepository {
  MockOnBoardingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> authenticate() =>
      (super.noSuchMethod(Invocation.method(#authenticate, []),
              returnValue: Future<_i2.Either<_i5.Failure, bool>>.value(
                  _FakeEither<_i5.Failure, bool>()))
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> checkCachedAuth() =>
      (super.noSuchMethod(Invocation.method(#checkCachedAuth, []),
              returnValue: Future<_i2.Either<_i5.Failure, bool>>.value(
                  _FakeEither<_i5.Failure, bool>()))
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
